"""
Plot which strategy (offset vs invest) is better over mortgage rate (x) and
return rate (y). Data generated by strategy-heatmap.ts.
"""
import json
import pathlib
import subprocess
import sys

import matplotlib.pyplot as plt
import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPT_PATH = ROOT / "scripts" / "strategy-heatmap.ts"
DATA_PATH = ROOT / "scripts" / "strategy-heatmap.json"
OUTPUT_PATH = ROOT / "scripts" / "strategy-heatmap.png"


def main() -> int:
    result = subprocess.run(
        ["npx", "tsx", str(SCRIPT_PATH)],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )
    data = json.loads(result.stdout)
    DATA_PATH.write_text(json.dumps(data, indent=2))

    mortgage_rates = np.array(data["mortgageRatesPct"])
    return_rates = np.array(data["returnRatesPct"])
    winner_grid = np.array(data["winnerGrid"])
    years = data["years"]

    # 1 = offset, 0 = invest (for colormap)
    strategy_values = np.where(winner_grid == "offset", 1, 0)

    fig, ax = plt.subplots(figsize=(10, 8))

    # winner_grid[i, j] = winner at (return_rates[i], mortgage_rates[j])
    # origin='lower' so row 0 (low return) at bottom
    mesh = ax.imshow(
        strategy_values,
        extent=[
            mortgage_rates[0],
            mortgage_rates[-1],
            return_rates[0],
            return_rates[-1],
        ],
        origin="lower",
        aspect="equal",
        cmap=plt.cm.RdYlBu_r,
        vmin=0,
        vmax=1,
        interpolation="nearest",
    )

    ax.set_xlabel("Mortgage interest rate (%)", fontsize=12)
    ax.set_ylabel("Investment return rate (%)", fontsize=12)
    ax.set_title(
        f"Better strategy after {years} years (Offset vs Invest)",
        fontsize=14,
        fontweight="bold",
    )
    ax.text(
        0.99,
        0.01,
        f"Source: project model (default inputs, {years}y horizon)",
        transform=ax.transAxes,
        fontsize=8,
        ha="right",
        va="bottom",
        alpha=0.8,
    )

    cbar = fig.colorbar(mesh, ax=ax, ticks=[0.25, 0.75])
    cbar.ax.set_yticklabels(["Invest", "Offset"])
    cbar.set_label("Better strategy", fontsize=11)

    # Boundary line where strategies tie
    ax.contour(
        mortgage_rates,
        return_rates,
        strategy_values,
        levels=[0.5],
        colors="black",
        linewidths=1.5,
    )

    plt.tight_layout()
    plt.savefig(OUTPUT_PATH, dpi=150)
    plt.close()

    print(f"Wrote data to {DATA_PATH}")
    print(f"Wrote chart to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
